# Generated by Django 6.1 on 2026-08-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='prio_name',
            new_name='Priority_Name',
        ),
    ]
