# Generated by Django 6.1 on 2026-09-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_prio_name_priority_priority_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='Priority_Name',
            new_name='priority_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.task'),
        ),
    ]
